### ISSUE TITLE
Error importing VISION_API_KEY from 'access-config'

### ISSUE THREAD

**Issue by rsk12** [kareemf/allergenify#1]
Hello kareem ,
                     Error importing VISION_API_KEY from 'access-config' in ocr.ts whether it should be importing api key from access-config containing google vision key.
Even remaining functionalities are not working as per the instructions in README given.

**Comment by rsk12** [comment]
Can you help me with this application for small personal use

**Comment by kareemf** [comment]
Hi @rsk12, thanks for reporting. As you can see, this project is pretty dated :). I'll take a look this week.

**Comment by rsk12** [comment]
Sure @kareemf Thanks for the reply.It would be great if its works.
Looking forward to it.

**Comment by rsk12** [comment]
Make Sure help me with this application , Very useful resource for me and helpful thank you .

**Comment by rsk12** [comment]
Is it revised @kareemf ?

**Comment by rsk12** [comment]
Hello  @kareemf its very important for my personal diet restriction ,Can you please resolve the issue.Thank you .
Make Sure to help seeing this code since 20 days to get resolved .

**Comment by rsk12** [comment]
Hello @kareemf ,may be access-config file has been ignored in gitignore . 
But access-config has VISION_API_KEY which is derived from google vision api , 
although put google vision api key in access-config or putting api key in .env is not working .
Checked each and every chance by putting api key but  camera capture failed , text form image not extracting ,alerts failed

**Comment by kareemf** [comment]
> Hello @kareemf ,may be access-config file has been ignored in gitignore .
Yeah, I thought I'd included that in the README, but it looks like I missed that step. I don't commit that file to the repo because it contains a private key that, as you have no doubt realized, should not be shared publicly on GH. You can create that file and drop that key and any other inexplicably missing keys there.

> ...although put google vision api key in access-config or putting api key in .env is not working .
Checked each and every chance by putting api key but camera capture failed , text form image not extracting ,alerts failed

I'm not sure if the API version that I used for this project is still supported, since its a couple years old now. You may have to check if the current documentation matches the code

> Hello @kareemf its very important for my personal diet restriction ,Can you please resolve the issue.Thank you .
You have to remember that this is an open source project, and a dormant one at that. If it is urgent, I'd welcome a pull request and you are also free to fork the project.

**Comment by rsk12** [comment]
Tried like this by 

export constant access-config{

VISION_API_KEY:'api_key';

}

import it in to ocr.ts file 


but no result

**Comment by rsk12** [comment]
API version that you have used ?

**Comment by kareemf** [comment]
Here's the content of `src/providers/ocr/access-config.ts`, which indicates that I used API version v1

```
export const VISION_ACCESS_TOKEN = 'ya29.c.....';
export const VISION_API_KEY = 'A....-U';


// curl -v -s -H "Content-Type: application/json" \
// https://vision.googleapis.com/v1/images:annotate?key=A....-U \
// --data-binary @request.json


// curl 'https://vision.googleapis.com/v1/images:annotate?key=A....-U' \
// -H 'origin: http://localhost:8100' \
// -H 'accept-encoding: gzip, deflate, br' \
// -H 'accept-language: en-US,en;q=0.9' \
// -H 'x-chrome-uma-enabled: 1' \
// -H 'x-client-data: ....=' \
// -H 'pragma: no-cache' \
// -H 'user-agent: ...' \
// -H 'content-type: application/json' \
// -H 'accept: application/json, text/plain, */*' \
// -H 'cache-control: no-cache' \
// -H 'authority: vision.googleapis.com' \
// -H 'referer: http://localhost:8100/' \
// -H 'dnt: 1' \
// --data-binary '{"requests":[{"image":{"content":""},"features":[{"type":0,"maxResults":1}]}]}' \
// --compressed
```

**Comment by rsk12** [comment]
Can you give those keys used in above file. 
I have generated API_KEY from google cloud vision 
used generated API_KEY but its not working.
How to generate VISION_ACCESS_TOKEN

**Comment by rsk12** [comment]
generated VISION_ACCESS_TOKEN
But the issue is same

**Comment by rsk12** [comment]
I have speaken with google cloud tech support  and asked about If V1 is still supported which released in 2017 ?
They have said it still supported.
